language: php

php:
  - 5.6

sudo: false

before_install: composer selfupdate

install: travis_retry composer install --no-interaction --prefer-source

before_script:
   - mysql -e 'create database travis;'
   - php artisan migrate:install
   - php artisan migrate:refresh --seed

script: vendor/bin/phpunit

notifications:
  slack:
    secure: Dws5+spWCvfCMCflZywFq09MYld8gv4xccJG0pLhw08oerCJHsiAqWNJBr+GlCwCVXqkls7AdmDYye+B27dPQBv/akx2f4StLJ7vQmSWVgnYn0reDa16+VUkRfQ32Csbj7Y0OR7/2Z3uePaS8vX/g1QbII0Y7GNIhIVce3TVeck=
    on_success: never
