language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

sudo: false

before_install: composer selfupdate

install: travis_retry composer install --no-interaction --prefer-source

before_script:
   - sleep 10
   - mysql -e 'create database travis;'
   - php artisan migrate:install
   - php artisan migrate:refresh --seed
   - php -r "copy('.env.example', '.env');"
   - php artisan key:generate

script:
 - phpunit --coverage-clover=.clover

after_script:
 - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
 - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover .clover; fi

notifications:
  slack:
    secure: Dws5+spWCvfCMCflZywFq09MYld8gv4xccJG0pLhw08oerCJHsiAqWNJBr+GlCwCVXqkls7AdmDYye+B27dPQBv/akx2f4StLJ7vQmSWVgnYn0reDa16+VUkRfQ32Csbj7Y0OR7/2Z3uePaS8vX/g1QbII0Y7GNIhIVce3TVeck=
    on_success: never
