language: php

php:
  - 7.0

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true  
  - composer selfupdate

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
   - sleep 10
   - mysql -e 'create database travis;'
   - php artisan migrate:install
   - php artisan migrate:refresh --seed
   - php -r "copy('.env.example', '.env');"
   - php artisan key:generate

script:
 - phpunit

notifications:
  slack:
    secure: Dws5+spWCvfCMCflZywFq09MYld8gv4xccJG0pLhw08oerCJHsiAqWNJBr+GlCwCVXqkls7AdmDYye+B27dPQBv/akx2f4StLJ7vQmSWVgnYn0reDa16+VUkRfQ32Csbj7Y0OR7/2Z3uePaS8vX/g1QbII0Y7GNIhIVce3TVeck=
    on_success: never
